### ISSUE TITLE
Sección Atributos

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/catalog-biodiversity-temp-backend#27]
El usuario no puede borrar el estado de amenaza según categorías UICN

![image](https://cloud.githubusercontent.com/assets/7827998/3306101/b5f895e6-f65d-11e3-86ca-2bf3412ff252.png)

Los demás atributos si los deja borrar, pero primero aparece el error anterior

**Comment by danipilze** [comment]
fixed already, right?

**Comment by nestorjal** [comment]
Fixed!
