### ISSUE TITLE
Sección Atributos perfil administrador

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/catalog-biodiversity-temp-backend#32]
- El administrador no puede borrar los campos creados en el estado de amenaza según categorías UICN (en el mundo)
- Se pueden ingresar los campos en esta sección pero no se visualizan cuando se da click en el botón guardar, es necesario dar click en actualizar y revisar la ficha para observar los cambios efectuados. 
- Así cómo en las secciones pasadas, cuando se intenta borrar un atributo aparece el mismo error, pero después de actualizar el cambio se ha efectuado correctamente.

![image](https://cloud.githubusercontent.com/assets/7827998/3306266/566f5a5e-f65f-11e3-8a96-7b03c7618d3c.png)

**Comment by danipilze** [comment]
is this fixed?

**Comment by mardeles** [comment]
Resuelto
